version: '2'
services:
  server:
    build:
      context: ./server/
    env_file: 
      - ./keys.env
    ports:
      - "8080:8080"
  client:
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    links:
      - server
    ports:
      - "3000:3000"